

version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Thong@123
      - POSTGRES_DB=outlet_0001
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:Cp6L7XXTPkXJpsVXcCm6@pos-api-service.ci5bs4qfk9kq.ap-southeast-1.rds.amazonaws.com/outlet_0001
    depends_on:
      - postgres
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]