// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateMenuCategory(ctx context.Context, arg CreateMenuCategoryParams) (TblMenuCategory, error)
	CreateMenuGroup(ctx context.Context, arg CreateMenuGroupParams) (TblMenuGroup, error)
	CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (TblMenuItem, error)
	CreateMenuItemDetail(ctx context.Context, arg CreateMenuItemDetailParams) (TblMenuItemDetail, error)
	CreateMenuSize(ctx context.Context, arg CreateMenuSizeParams) (TblMenuSize, error)
	CreateOutlet(ctx context.Context, arg CreateOutletParams) (TblOutlet, error)
	CreatePrinter(ctx context.Context, arg CreatePrinterParams) (TblPrinter, error)
	CreateTerminal(ctx context.Context, arg CreateTerminalParams) (TblTerminal, error)
	DeleteMenuCategory(ctx context.Context, id int64) error
	DeleteMenuGroup(ctx context.Context, arg DeleteMenuGroupParams) error
	DeleteMenuItem(ctx context.Context, id int64) error
	DeleteMenuSize(ctx context.Context, arg DeleteMenuSizeParams) error
	DeleteOutlet(ctx context.Context, arg DeleteOutletParams) error
	DeletePrinter(ctx context.Context, arg DeletePrinterParams) error
	DeleteTerminal(ctx context.Context, arg DeleteTerminalParams) error
	GetMenuCategories(ctx context.Context, arg GetMenuCategoriesParams) ([]TblMenuCategory, error)
	GetMenuCategory(ctx context.Context, id int64) (TblMenuCategory, error)
	GetMenuGroup(ctx context.Context, id int64) (TblMenuGroup, error)
	GetMenuGroups(ctx context.Context, arg GetMenuGroupsParams) ([]TblMenuGroup, error)
	GetMenuItem(ctx context.Context, id int64) (TblMenuItem, error)
	GetMenuItems(ctx context.Context, arg GetMenuItemsParams) ([]TblMenuItem, error)
	GetMenuSize(ctx context.Context, id int64) (TblMenuSize, error)
	GetMenuSizes(ctx context.Context, arg GetMenuSizesParams) ([]TblMenuSize, error)
	GetOutlet(ctx context.Context, id int64) (TblOutlet, error)
	GetOutlets(ctx context.Context, arg GetOutletsParams) ([]TblOutlet, error)
	GetPrinter(ctx context.Context, id int64) (TblPrinter, error)
	GetPrinters(ctx context.Context, arg GetPrintersParams) ([]TblPrinter, error)
	GetTerminal(ctx context.Context, id int64) (TblTerminal, error)
	GetTerminals(ctx context.Context, arg GetTerminalsParams) ([]TblTerminal, error)
	UpdateMenuCategory(ctx context.Context, arg UpdateMenuCategoryParams) error
	UpdateMenuGroup(ctx context.Context, arg UpdateMenuGroupParams) error
	UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) error
	UpdateMenuSize(ctx context.Context, arg UpdateMenuSizeParams) error
	UpdateOutlet(ctx context.Context, arg UpdateOutletParams) error
	UpdatePrinter(ctx context.Context, arg UpdatePrinterParams) error
	UpdateTerminal(ctx context.Context, arg UpdateTerminalParams) error
}

var _ Querier = (*Queries)(nil)
