
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-api-deployment
  labels:
    app: pos-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pos-api
  template:
    metadata:
      labels:
        app: pos-api
    spec:
      containers:
      - name: pos-api
        image: 420122552625.dkr.ecr.ap-southeast-1.amazonaws.com/pos-api-service:d0530e429d265ac878a766fa6c800654bbe06502
        imagePullPolicy: Always
        ports:
        - containerPort: 8080