
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-api-deployment
  labels:
    app: pos-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pos-api
  template:
    metadata:
      labels:
        app: pos-api
    spec:
      containers:
      - name: pos-api
        image: 420122552625.dkr.ecr.ap-southeast-1.amazonaws.com/pos-api-service:99471cb348fe4d561e95e9a734bd52696e438a8c
        imagePullPolicy: Always
        ports:
        - containerPort: 8080